# Generated by Django 4.1.5 on 2023-01-31 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="listItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_display_text", models.CharField(max_length=200)),
                ("item_type", models.CharField(max_length=200)),
                ("item_contents", models.JSONField()),
            ],
        ),
    ]
